name: google_charts
version: 0.2.1
author: Robert Hartung <robert.w.hartung@gmail.com>
description: Google Charts API Wrapper Classes.
homepage: https://github.com/roberthartung/google_charts
environment:
    sdk: ">=1.8.0 <2.0.0"
dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0-rc.17
  web_components: ^0.12.0
  reflectable: ^0.5.4
dev_dependencies:
  html: any
  http: any
transformers:
- web_components:
    entry_points:
    - example/polymer/donutchart/index.html
    - example/polymer/table/index.html
- reflectable:
    entry_points:
    - example/polymer/donutchart/index.dart
    - example/polymer/table/index.dart
